apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-files
  labels:
    type: local
spec:
  volumeMode: Filesystem
  storageClassName: nd-files-storage
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: "/mnt/nextcloud/postgres-storage"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - vmi856836.contaboserver.net # The name of your nod

