apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-postgres
  labels:
    type: 'local'
spec:
  storageClassName: nd-postgres-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: "/mnt/nextcloud/postgres-storage"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - vmi856836.contaboserver.net # The name of your nod


