# Default values for my-academy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
ingress:
  host: "myjiujitsuacademy.com"
  secretName: academy-ingress-secret
  certificateName: academy-ingress-cert

landingPage:
  image: "vaggelas/my-public-pages:11.0"

nextcloud:
  host: 'nextcloud.myjiujitsuacademy.com'
  username: admin
  password: CCQBqL^wX@vs!4#s
  persistence:
    enabled: true
    storageClass: nd-files-storage
  lifecycle:
    postStartCommand: [ "/bin/sh", "-c", "echo \"ServerName my-academy-nextcloud\" | tee -a /etc/apache2/apache2.conf" ]
  resources:
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    limits:
      cpu: 600m
      memory: 8Gi
    requests:
      cpu: 500m
      memory: 1Gi
  internalDatabase:
    enabled: false

  configs:
    custom.config.php: |-
      <?php
      $CONFIG = array (
        'trusted_domains' =>
        array (
          0 => 'nextcloud.myjiujitsuacademy.com',
        ),
        'trusted_proxies' =>
        array (
          0 => '164.68.98.211',
        ),
        
      );
  postgresql:

    enabled: true
    global:
      postgresql:
        auth:
          username: nextcloud
          password: z^WqDhDyE%y8dWX3
          database: nextcloud
          postgresPassword: "*VR!$hE8L6&cToLF"

    primary:
      containerSecurityContext:
        enabled: true
        runAsUser: 1000
      podSecurityContext:
        enabled: true
        fsGroup: 2000
      persistence:

        enabled: true
        storageClass: nd-postgres-storage





